before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    binary: greeter
    ldflags:
      - -s -w
    goos:
      - linux
    goarch:
      - amd64
archives:
- files:
    - LICENSE
    - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
